### ISSUE TITLE
[Bug] no module into "The Forge"

### ISSUE THREAD

**Issue by Gabryel666** [erizocosmico/foundryvtt-polished-ui#1]
I'm not sure if the problem is with the module. 

I install on the platform "The Forge" the module. This one appears well as installed module.

![image](https://user-images.githubusercontent.com/65908230/188903061-880431e1-dce5-4c38-a98c-87f33e29addf.png)

When I go into the game in the menu configuration of modules, I am not in the list polished UI.

![image](https://user-images.githubusercontent.com/65908230/188901851-063d9838-bf18-448c-b21e-acf47b99436c.png)

Thx

**Comment by erizocosmico** [comment]
Hey, thanks for reporting this issue!

I don't have a Forge installation to test on, but I just tried on a local installation and it seems to work. I see your Foundry language is French, can you switch to english and see if it works that way? It might be an error due to not having the language file for french. If that's the case I will just add the french translation to solve the issue.

**Comment by Gabryel666** [comment]
Thx for your quick answer !
I tried switching to English but it's the same. The module seems to be installed on the forge side but I can't see it in the module list from the game.
Ma version :
<img width="221" alt="image" src="https://user-images.githubusercontent.com/65908230/188996257-c7622d01-4509-4ad3-9018-ee9b324b33a9.png">

**Comment by erizocosmico** [comment]
Ah! I see you're using version 10. I have not upgraded yet from V9 and haven't tested this on V10. Will try it and see if that's the problem.

**Comment by Gabryel666** [comment]
This is often a missing information on modules on github. Maybe you could specify the compatible version on the homepage of the module? Thanks again

**Comment by erizocosmico** [comment]
I've just tested it on V10 and seems to work fine. The only other thing I can think of is that Forge may not have installed a module dependency this module has.

Do you have the `lib - ColorSettings` module installed? 

EDIT: Just made a Forge account and seems to work fine on V10 for me

**Comment by Gabryel666** [comment]
New version is ok ! Thanks a lot !

**Comment by erizocosmico** [comment]
Great! Thanks for reporting!
