### ISSUE TITLE
V10 - A/V Dock

### ISSUE THREAD

**Issue by hlmodking** [erizocosmico/foundryvtt-polished-ui#2]
When module is active; ALL controls for foundry AV user dock UI are not accessible/visible, additionally if video is disabled there is no way to reenable coms unless module is disabled, video reset and module turned back on. (this is due to lack of controls). 

Fantastic module otherwise, thanks for the work!

**Comment by erizocosmico** [comment]
Fixed! v1.0.6 works fine now with A/V dock.

Thanks for reporting!
