### ISSUE TITLE
[Feature] Control shadow size

### ISSUE THREAD

**Issue by Gabryel666** [erizocosmico/foundryvtt-polished-ui#3]
It would be interesting to have in future releases the possibility to reduce the size of the shadow on the right menu.
It's very nice now, but depending on the scene the shadow can sometimes go over the scene itself.
Congratulations again for this UI, the design customization modules were really missing in Foundry.

**Comment by erizocosmico** [comment]
Sounds good! Will add it once i have time to work on this

**Comment by erizocosmico** [comment]
v1.1.0 adds support for a smaller sidebar with less shadow!

**Comment by Gabryel666** [comment]
Nice :) thanks !
