### ISSUE TITLE
Update Bug

### ISSUE THREAD

**Issue by brunocalado** [erizocosmico/foundryvtt-polished-ui#5]
Every time you click update you got this:

![image](https://user-images.githubusercontent.com/4999783/195867814-3c607feb-fc76-4963-9255-efea3bd10f65.png)

**Comment by erizocosmico** [comment]
Thanks for reporting! I will take a look at this issue as soon as possible

**Comment by erizocosmico** [comment]
Fixed in v1.1.2!
